spring:
  application:
    name: Hawthorne-REST
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  config:
    import: application-security.yaml
springdoc:
  swagger-ui:
    path: /openapi